### Create Incident 1
POST http://localhost:8080/api/incidents
Content-Type: application/json

{
  "title": "Database Down",
  "description": "Postgres is not responding",
  "severity": "HIGH"
}

###

POST http://localhost:8080/api/incidents
Content-Type: application/json

{
  "title": "Worker Node Not Ready",
  "description": "Node entered NotReady state",
  "severity": "CRITICAL"
}

###

POST http://localhost:8080/api/incidents
Content-Type: application/json

{
  "title": "Ingress Failure",
  "description": "404 from ingress",
  "severity": "MEDIUM"
}

### Get all incidents
GET http://localhost:8080/api/incidents