apiVersion: apps/v1

kind: Deployment

metadata:
  name: kubesentry
  namespace: kubesentry
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: kubesentry

  template:

    metadata:
      labels:
        app: kubesentry
    spec:
      serviceAccountName: kubesentry-sa

      containers:
        - name: kubesentry
          image: yashpandeywork/kubesentry:v3
          imagePullPolicy: IfNotPresent
          env:

            # From ConfigMap
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: kubesentry-config
                  key: SPRING_DATASOURCE_URL

            # From Secret
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"


