apiVersion: v1

kind: Service

metadata:
  name: kubesentry-service
  namespace: kubesentry
spec:

  selector:
    app: kubesentry

  ports:

    - protocol: TCP
      port: 80
      targetPort: 8080

  type: NodePort