apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: kubesentry-reader
  namespace: kubesentry

rules:

  # Read Pods
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

  # Read Services
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
      - list
      - watch

  # Read ConfigMaps
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch

  # Read Events
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - get
      - list
      - watch